<?php
/**
 * Date: 12/11/2018
 * Time: 12:37 PM
 */

/*
 * --- Day 10: The Stars Align ---
 * It's no use; your navigation system simply isn't capable of providing walking directions in the arctic circle, and certainly not in 1018.
 *
 * The Elves suggest an alternative. In times like these, North Pole rescue operations will arrange points of light in the sky to guide missing Elves back to base. Unfortunately, the message is easy to miss: the points move slowly enough that it takes hours to align them, but have so much momentum that they only stay aligned for a second. If you blink at the wrong time, it might be hours before another message appears.
 *
 * You can see these points of light floating in the distance, and record their position in the sky and their velocity, the relative change in position per second (your puzzle input). The coordinates are all given from your perspective; given enough time, those positions and velocities will move the points into a cohesive message!
 *
 * Rather than wait, you decide to fast-forward the process and calculate what the points will eventually spell.
 *
 * For example, suppose you note the following points:
 *
 * position=< 9,  1> velocity=< 0,  2>
 * position=< 7,  0> velocity=<-1,  0>
 * position=< 3, -2> velocity=<-1,  1>
 * position=< 6, 10> velocity=<-2, -1>
 * position=< 2, -4> velocity=< 2,  2>
 * position=<-6, 10> velocity=< 2, -2>
 * position=< 1,  8> velocity=< 1, -1>
 * position=< 1,  7> velocity=< 1,  0>
 * position=<-3, 11> velocity=< 1, -2>
 * position=< 7,  6> velocity=<-1, -1>
 * position=<-2,  3> velocity=< 1,  0>
 * position=<-4,  3> velocity=< 2,  0>
 * position=<10, -3> velocity=<-1,  1>
 * position=< 5, 11> velocity=< 1, -2>
 * position=< 4,  7> velocity=< 0, -1>
 * position=< 8, -2> velocity=< 0,  1>
 * position=<15,  0> velocity=<-2,  0>
 * position=< 1,  6> velocity=< 1,  0>
 * position=< 8,  9> velocity=< 0, -1>
 * position=< 3,  3> velocity=<-1,  1>
 * position=< 0,  5> velocity=< 0, -1>
 * position=<-2,  2> velocity=< 2,  0>
 * position=< 5, -2> velocity=< 1,  2>
 * position=< 1,  4> velocity=< 2,  1>
 * position=<-2,  7> velocity=< 2, -2>
 * position=< 3,  6> velocity=<-1, -1>
 * position=< 5,  0> velocity=< 1,  0>
 * position=<-6,  0> velocity=< 2,  0>
 * position=< 5,  9> velocity=< 1, -2>
 * position=<14,  7> velocity=<-2,  0>
 * position=<-3,  6> velocity=< 2, -1>
 * Each line represents one point. Positions are given as <X, Y> pairs: X represents how far left (negative) or right (positive) the point appears, while Y represents how far up (negative) or down (positive) the point appears.
 *
 * At 0 seconds, each point has the position given. Each second, each point's velocity is added to its position. So, a point with velocity <1, -2> is moving to the right, but is moving upward twice as quickly. If this point's initial position were <3, 9>, after 3 seconds, its position would become <6, 3>.
 *
 * Over time, the points listed above would move like this:
 *
 * Initially:
 * ........#.............
 * ................#.....
 * .........#.#..#.......
 * ......................
 * #..........#.#.......#
 * ...............#......
 * ....#.................
 * ..#.#....#............
 * .......#..............
 * ......#...............
 * ...#...#.#...#........
 * ....#..#..#.........#.
 * .......#..............
 * ...........#..#.......
 * #...........#.........
 * ...#.......#..........
 *
 * After 1 second:
 * ......................
 * ......................
 * ..........#....#......
 * ........#.....#.......
 * ..#.........#......#..
 * ......................
 * ......#...............
 * ....##.........#......
 * ......#.#.............
 * .....##.##..#.........
 * ........#.#...........
 * ........#...#.....#...
 * ..#...........#.......
 * ....#.....#.#.........
 * ......................
 * ......................
 *
 * After 2 seconds:
 * ......................
 * ......................
 * ......................
 * ..............#.......
 * ....#..#...####..#....
 * ......................
 * ........#....#........
 * ......#.#.............
 * .......#...#..........
 * .......#..#..#.#......
 * ....#....#.#..........
 * .....#...#...##.#.....
 * ........#.............
 * ......................
 * ......................
 * ......................
 *
 * After 3 seconds:
 * ......................
 * ......................
 * ......................
 * ......................
 * ......#...#..###......
 * ......#...#...#.......
 * ......#...#...#.......
 * ......#####...#.......
 * ......#...#...#.......
 * ......#...#...#.......
 * ......#...#...#.......
 * ......#...#..###......
 * ......................
 * ......................
 * ......................
 * ......................
 *
 * After 4 seconds:
 * ......................
 * ......................
 * ......................
 * ............#.........
 * ........##...#.#......
 * ......#.....#..#......
 * .....#..##.##.#.......
 * .......##.#....#......
 * ...........#....#.....
 * ..............#.......
 * ....#......#...#......
 * .....#.....##.........
 * ...............#......
 * ...............#......
 * ......................
 * ......................
 * After 3 seconds, the message appeared briefly: HI. Of course, your message will be much longer and will take many more seconds to appear.
 *
 * What message will eventually appear in the sky?
 *
 *  */

// * start the run timer for the first part
$time_start = microtime(true);

// bunch of variables
$puzzle_data_raw = [];
$puzzle_data = $puzzle_data2 = [];
$area_current = $area_last = PHP_INT_MAX;
$seconds_passed = 0;
$seconds_min_area = 0;
$dimensions_last = $dimensions_current = [];
$display_data = [];

// capture puzzle data
$puzzle_data_raw = file('day10datasmallset');
foreach($puzzle_data_raw as $row) {
    preg_match_all('/(-?\d+)/',$row,$matches);
    $puzzle_data[] = $puzzle_data2[] =$matches[0];
}

// find the second at which the set is transformed to its smallest size
while($area_current<=$area_last){
    $area_last = $area_current;
    $dimensions_last = $dimensions_current;
    $dimensions_current = one_second_transform($puzzle_data, $seconds_passed);
    $area_current = $dimensions_current['minArea'];
    ++$seconds_passed;
};
$seconds_min_area = $seconds_passed - 1;

print_r($dimensions_last);
print_r($dimensions_current);


// find the minX and minY for the smallest set, and their offset from (0,0)

//echo "minX is : "  . $dimensions_last['minX'] . PHP_EOL;
//echo "minY is : " . $dimensions_last['minY'] . PHP_EOL;

//foreach($puzzle_data as $row){
//    $display_data[$row[0]-$dimensions_last['minX']][] = $row[1]-$dimensions_last['minY'];
//}
//print_r($display_data);

function one_second_transform(&$puzzle_data,$seconds_passed){
    foreach($puzzle_data as $key=>$line) {
        $puzzle_data[$key][0] += $line[2] * $seconds_passed;
        $puzzle_data[$key][1] += $line[3] * $seconds_passed;
    }

    $minX = min(array_column($puzzle_data,0));
    $maxX = max(array_column($puzzle_data,0));
    $minY = min(array_column($puzzle_data,1));
    $maxY = max(array_column($puzzle_data,1));
    $minArea = abs($minX - $maxX) * abs($minY - $maxY);

    return array(
        'minX' => $minX,
        'maxX' => $maxX,
        'minY' => $minY,
        'maxY' => $maxY,
        'minArea'=> $minArea
    );
}

// * stop the run timer for the first part
echo "Runtime 1 (seconds): " . (microtime(true) - $time_start) . "\n";

